### PR TITLE
pkgdown website

### PR DESCRIPTION
**Pull request by espinielli**
David,
this PR is for the pkgdown website for `himach`.
I did it in my fork (I do not have write rights in the david6marsh/himach repo) and you can see a preview in https://espinielli.github.io/himach/

When merging there are few further things to change:
1. DESCRIPTION should mention https://david6marsh.github.io/himach/ instead of https://espinielli.github.io/himach/
2. I think the setting of david6marsh/himach repo should properly configure to serve GitHub Pages from gh-pages branch

HTH

### CODE REVIEW

**Comment by david6marsh** [comment]
Looks great. Thanks.

**Comment by espinielli** [comment]
you still need to 
1. change `_pkgdown.yml` with the right URL, i.e. `https://david6marsh.github.io/himach/`
2. regenerate everything: `pkgdown::build_site()`
3. change the preference for the repo to serve the GitHub Pages from the `main/docs` directory

or something like that ;-)

**Comment by espinielli** [comment]
David,
I re-triggered the pkgdown GHA and it worked.

You now need to enable GitHub Pages in the Preferences (I have no access to this) so that what is produced in the `gh-pages` branch (the pkgdown of himach) is published on the web at `https://david6marsh.github.io/himach/`

**Comment by espinielli** [comment]
Here are the settings (from my fork, what is important is the yellow arrow):
Screenshot 2023-10-13 at 11 50 37

**Comment by david6marsh** [comment]
Hooray - it’s there now. Maybe it just took a while to build in the new location.

Thanks for your patience!

David

**Comment by espinielli** [comment]
You can now add the relevant URL in the repo prefs, like
image

**Pull request merged**
